#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Combine individual chapter .docx files generated by export_chapters_to_word.py
into a single Word document for the full PresbyCor book.

Uses docxcompose for correct image/style merging.
Install: pip install docxcompose
"""
import sys, io
from pathlib import Path
from docx import Document
from docx.shared import Pt
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

try:
    from docxcompose.composer import Composer
except ImportError:
    print("[ERROR] docxcompose não instalado. Execute: pip install docxcompose")
    sys.exit(1)

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent
OUTPUT_DIR = PROJECT_ROOT / "_Distributable_Book" / "Word_Editorial"

# Order of files (preface then chapters 1-13, including 5+)
FILE_ORDER = [
    "PresbyCor_Preface_Editorial.docx",
    "PresbyCor_Chapter_01_Editorial.docx",
    "PresbyCor_Chapter_02_Editorial.docx",
    "PresbyCor_Chapter_03_Editorial.docx",
    "PresbyCor_Chapter_04_Editorial.docx",
    "PresbyCor_Chapter_05_Editorial.docx",
    "PresbyCor_Chapter_05Plus_Editorial.docx",
    "PresbyCor_Chapter_06_Editorial.docx",
    "PresbyCor_Chapter_07_Editorial.docx",
    "PresbyCor_Chapter_08_Editorial.docx",
    "PresbyCor_Chapter_09_Editorial.docx",
    "PresbyCor_Chapter_10_Editorial.docx",
    "PresbyCor_Chapter_11_Editorial.docx",
    "PresbyCor_Chapter_12_Editorial.docx",
    "PresbyCor_Chapter_13_Editorial.docx",
]

def add_page_break(doc: Document):
    """Adds a page break paragraph to the document."""
    para = doc.add_paragraph()
    run = para.add_run()
    br = OxmlElement('w:br')
    br.set(qn('w:type'), 'page')
    run._r.append(br)


# ── Iniciar com o primeiro arquivo como base ──────────────────────────────────
first_file = None
for fname in FILE_ORDER:
    fpath = OUTPUT_DIR / fname
    if fpath.exists():
        first_file = fpath
        break

if first_file is None:
    print("[ERROR] Nenhum arquivo encontrado. Verifique o diretório de saída.")
    sys.exit(1)

print(f"[PresbyCor] Combinando livro completo...")
print(f"[Base]  {first_file.name}")

master = Document(str(first_file))
composer = Composer(master)

# ── Adicionar capítulos restantes ─────────────────────────────────────────────
found_first = False
for idx, fname in enumerate(FILE_ORDER):
    fpath = OUTPUT_DIR / fname
    if not fpath.exists():
        print(f"  [WARN] Ausente, pulando: {fname}")
        continue

    if not found_first:
        found_first = True
        print(f"  [OK]  {fname} (base)")
        continue  # já é o master

    print(f"  [OK]  {fname}")
    # Adicionar quebra de página entre capítulos
    add_page_break(master)
    # Combinar preservando imagens, estilos e relações
    doc_to_add = Document(str(fpath))
    composer.append(doc_to_add)

# ── Salvar ────────────────────────────────────────────────────────────────────
combined_path = OUTPUT_DIR / "PresbyCor_Full_Editorial.docx"
composer.save(str(combined_path))
size_mb = combined_path.stat().st_size / (1024 * 1024)
print(f"\n[INFO] Documento combinado salvo: {combined_path.name} ({size_mb:.1f} MB)")
print(f"[OK]   Imagens e estilos preservados via docxcompose.")
